name: Play_TicTacToe

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write

jobs:
  play:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/profile/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        if: hashFiles('.github/profile/requirements.txt') != ''
        run: pip install -r .github/profile/requirements.txt

      - name: Update game
        if: hashFiles('.github/profile/tictactoe.py') != ''
        run: python .github/profile/tictactoe.py
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Commit and push changes
        run: |
          git diff
          git add .
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git diff --cached --quiet || git commit -m "Updated game"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}